
services:
    postgres:
        image: postgres:13.4
        environment:
          - POSTGRES_USER=${MLFLOW_DB_USER}
          - POSTGRES_PASSWORD=${MLFLOW_DB_PASSWORD}
          - POSTGRES_DB=${MLFLOW_DB}
        ports:
          - '5438:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data